import 'package:pigeon/pigeon.dart';

@ConfigurePigeon(PigeonOptions(
  dartOut: 'lib/src/generated/extractor_api.g.dart',
  kotlinOut: 'android/src/main/kotlin/com/ottomancoder/newpipeextractor_dart/ExtractorApi.g.kt',
  kotlinOptions: KotlinOptions(
    package: 'com.ottomancoder.newpipeextractor_dart',
  ),
))

// ─── DTOs ────────────────────────────────────────────────

class VideoInfoDto {
  String? id;
  String? url;
  String? name;
  String? uploaderName;
  String? uploaderUrl;
  List<String?>? uploaderAvatars;
  String? uploadDate;
  String? description;
  int? length;
  int? viewCount;
  int? likeCount;
  int? dislikeCount;
  String? category;
  int? ageLimit;
  List<String?>? tags;
  List<String?>? thumbnails;
  String? streamType;
  String? hlsUrl;
  String? dashMpdUrl;
  bool? isShort;
  bool? isUploaderVerified;
  String? privacy;
  int? uploaderSubscriberCount;
  String? subChannelName;
  String? subChannelUrl;
  List<String?>? subChannelAvatars;
  String? licence;
  String? supportInfo;
}

class AudioStreamDto {
  String? url;
  int? averageBitrate;
  String? formatName;
  String? formatSuffix;
  String? formatMimeType;
  String? audioTrackName;
  String? audioTrackLocale;
  String? audioTrackType;
}

class VideoStreamDto {
  String? url;
  String? resolution;
  int? fps;
  String? formatName;
  String? formatSuffix;
  String? formatMimeType;
  bool? isVideoOnly;
}

class SubtitleStreamDto {
  String? url;
  String? format;
  String? locale;
  bool? isAutoGenerated;
}

class StreamInfoItemDto {
  String? url;
  String? id;
  String? name;
  String? uploaderName;
  String? uploaderUrl;
  List<String?>? uploaderAvatars;
  String? uploadDate;
  String? date;
  int? duration;
  int? viewCount;
  bool? isShort;
}

class ChannelInfoItemDto {
  String? url;
  String? name;
  String? description;
  List<String?>? thumbnails;
  int? subscriberCount;
  int? streamCount;
  bool? isVerified;
}

class PlaylistInfoItemDto {
  String? url;
  String? name;
  String? uploaderName;
  List<String?>? thumbnails;
  int? streamCount;
}

class ChannelDto {
  String? id;
  String? name;
  String? url;
  List<String?>? avatars;
  List<String?>? banners;
  String? description;
  String? feedUrl;
  int? subscriberCount;
  bool? isVerified;
  List<String?>? tabs;
}

class PlaylistDto {
  String? id;
  String? name;
  String? url;
  String? uploaderName;
  List<String?>? uploaderAvatars;
  String? uploaderUrl;
  List<String?>? banners;
  List<String?>? thumbnails;
  int? streamCount;
  String? description;
  String? playlistType;
}

class CommentDto {
  String? author;
  String? commentText;
  String? uploadDate;
  List<String?>? uploaderAvatars;
  String? uploaderUrl;
  String? commentId;
  int? likeCount;
  bool? hearted;
  bool? pinned;
  int? replyCount;
  bool? isChannelOwner;
  bool? isUploaderVerified;
  int? streamPosition;
}

class CommentsPageDto {
  List<CommentDto?>? comments;
  bool? hasNextPage;
}

class SegmentDto {
  String? url;
  String? title;
  String? previewUrl;
  int? startTimeSeconds;
}

class FramesetDto {
  List<String?>? urls;
  int? width;
  int? height;
  int? totalCount;
}

class StreamsDto {
  List<AudioStreamDto?>? audioStreams;
  List<VideoStreamDto?>? videoOnlyStreams;
  List<VideoStreamDto?>? videoStreams;
  List<SubtitleStreamDto?>? subtitleStreams;
  List<SegmentDto?>? segments;
  List<FramesetDto?>? framesets;
}

class SearchResultDto {
  List<StreamInfoItemDto?>? videos;
  List<PlaylistInfoItemDto?>? playlists;
  List<ChannelInfoItemDto?>? channels;
}

class TabPageDto {
  List<StreamInfoItemDto?>? items;
  bool? hasNextPage;
}

// ─── Host APIs ───────────────────────────────────────────

@HostApi()
abstract class VideoExtractorApi {
  @async
  VideoInfoDto getVideoInfo(String url);

  @async
  StreamsDto getVideoStreams(String url);

  @async
  List<SegmentDto?> getVideoSegments(String url);

  @async
  SearchResultDto getRelatedStreams(String url);
}

@HostApi()
abstract class SearchApi {
  @async
  SearchResultDto searchYoutube(String query, List<String?> filters);

  @async
  SearchResultDto getNextPage();

  @async
  SearchResultDto searchYoutubeMusic(String query, List<String?> filters);

  @async
  SearchResultDto getNextMusicPage();

  @async
  List<String?> getSearchSuggestions(String query);
}

@HostApi()
abstract class ChannelApi {
  @async
  ChannelDto getChannelInfo(String url);

  @async
  List<StreamInfoItemDto?> getChannelUploads(String url);

  @async
  List<StreamInfoItemDto?> getChannelNextPage();

  @async
  TabPageDto getChannelTabContent(String url, String tabFilter);

  @async
  TabPageDto getChannelTabNextPage();
}

@HostApi()
abstract class PlaylistApi {
  @async
  PlaylistDto getPlaylistDetails(String url);

  @async
  List<StreamInfoItemDto?> getPlaylistStreams(String url);

  @async
  List<StreamInfoItemDto?> getPlaylistNextPage();
}

@HostApi()
abstract class CommentsApi {
  @async
  CommentsPageDto getComments(String url);

  @async
  CommentsPageDto getNextCommentsPage();

  @async
  CommentsPageDto getCommentReplies(int commentIndex);
}

@HostApi()
abstract class TrendingApi {
  @async
  List<StreamInfoItemDto?> getTrendingVideos();

  @async
  List<String?> listKiosks();

  @async
  List<StreamInfoItemDto?> getKioskContent(String kioskId);
}

@HostApi()
abstract class UrlApi {
  @async
  String? getIdFromStreamUrl(String url);

  @async
  String? getIdFromPlaylistUrl(String url);

  @async
  String? getIdFromChannelUrl(String url);

  @async
  bool isValidStreamUrl(String url);

  @async
  bool isValidPlaylistUrl(String url);

  @async
  bool isValidChannelUrl(String url);
}

@HostApi()
abstract class CookieApi {
  @async
  void setCookie(String cookie);

  @async
  String? getCookieByUrl(String url);

  @async
  String? decodeCookie(String cookie);
}

@HostApi()
abstract class LocalizationApi {
  @async
  void setLocalization(String languageCode, String countryCode);
}

// ─── Multi-Service DTOs ─────────────────────────────────

class ServiceInfoDto {
  int? serviceId;
  String? name;
  String? baseUrl;
}

// ─── Multi-Service APIs ─────────────────────────────────

@HostApi()
abstract class ServiceApi {
  @async
  List<ServiceInfoDto?> getAvailableServices();
}

@HostApi()
abstract class ServiceStreamApi {
  @async
  VideoInfoDto getStreamInfo(int serviceId, String url);

  @async
  StreamsDto getStreams(int serviceId, String url);

  @async
  SearchResultDto getRelatedItems(int serviceId, String url);
}

@HostApi()
abstract class ServiceSearchApi {
  @async
  SearchResultDto search(int serviceId, String query, List<String?> filters);

  @async
  SearchResultDto searchNextPage(int serviceId);

  @async
  List<String?> getSuggestions(int serviceId, String query);
}

@HostApi()
abstract class ServiceChannelApi {
  @async
  ChannelDto getChannelInfo(int serviceId, String url);

  @async
  List<StreamInfoItemDto?> getChannelContent(int serviceId, String url);

  @async
  List<StreamInfoItemDto?> getChannelContentNextPage(int serviceId);
}

@HostApi()
abstract class ServicePlaylistApi {
  @async
  PlaylistDto getPlaylistInfo(int serviceId, String url);

  @async
  List<StreamInfoItemDto?> getPlaylistContent(int serviceId, String url);

  @async
  List<StreamInfoItemDto?> getPlaylistContentNextPage(int serviceId);
}

@HostApi()
abstract class ServiceKioskApi {
  @async
  List<String?> listServiceKiosks(int serviceId);

  @async
  List<StreamInfoItemDto?> getServiceKioskContent(int serviceId, String kioskId);
}
