// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.ottomancoder.newpipeextractor_dart

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer

private fun wrapResult(result: Any?): List<Any?> {
  return listOf(result)
}

private fun wrapError(exception: Throwable): List<Any?> {
  return if (exception is FlutterError) {
    listOf(
      exception.code,
      exception.message,
      exception.details
    )
  } else {
    listOf(
      exception.javaClass.simpleName,
      exception.toString(),
      "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
    )
  }
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

/** Generated class from Pigeon that represents data sent in messages. */
data class VideoInfoDto (
  val id: String? = null,
  val url: String? = null,
  val name: String? = null,
  val uploaderName: String? = null,
  val uploaderUrl: String? = null,
  val uploaderAvatars: List<String?>? = null,
  val uploadDate: String? = null,
  val description: String? = null,
  val length: Long? = null,
  val viewCount: Long? = null,
  val likeCount: Long? = null,
  val dislikeCount: Long? = null,
  val category: String? = null,
  val ageLimit: Long? = null,
  val tags: List<String?>? = null,
  val thumbnails: List<String?>? = null,
  val streamType: String? = null,
  val hlsUrl: String? = null,
  val dashMpdUrl: String? = null,
  val isShort: Boolean? = null,
  val isUploaderVerified: Boolean? = null,
  val privacy: String? = null,
  val uploaderSubscriberCount: Long? = null,
  val subChannelName: String? = null,
  val subChannelUrl: String? = null,
  val subChannelAvatars: List<String?>? = null,
  val licence: String? = null,
  val supportInfo: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): VideoInfoDto {
      val id = pigeonVar_list[0] as String?
      val url = pigeonVar_list[1] as String?
      val name = pigeonVar_list[2] as String?
      val uploaderName = pigeonVar_list[3] as String?
      val uploaderUrl = pigeonVar_list[4] as String?
      val uploaderAvatars = pigeonVar_list[5] as List<String?>?
      val uploadDate = pigeonVar_list[6] as String?
      val description = pigeonVar_list[7] as String?
      val length = pigeonVar_list[8] as Long?
      val viewCount = pigeonVar_list[9] as Long?
      val likeCount = pigeonVar_list[10] as Long?
      val dislikeCount = pigeonVar_list[11] as Long?
      val category = pigeonVar_list[12] as String?
      val ageLimit = pigeonVar_list[13] as Long?
      val tags = pigeonVar_list[14] as List<String?>?
      val thumbnails = pigeonVar_list[15] as List<String?>?
      val streamType = pigeonVar_list[16] as String?
      val hlsUrl = pigeonVar_list[17] as String?
      val dashMpdUrl = pigeonVar_list[18] as String?
      val isShort = pigeonVar_list[19] as Boolean?
      val isUploaderVerified = pigeonVar_list[20] as Boolean?
      val privacy = pigeonVar_list[21] as String?
      val uploaderSubscriberCount = pigeonVar_list[22] as Long?
      val subChannelName = pigeonVar_list[23] as String?
      val subChannelUrl = pigeonVar_list[24] as String?
      val subChannelAvatars = pigeonVar_list[25] as List<String?>?
      val licence = pigeonVar_list[26] as String?
      val supportInfo = pigeonVar_list[27] as String?
      return VideoInfoDto(id, url, name, uploaderName, uploaderUrl, uploaderAvatars, uploadDate, description, length, viewCount, likeCount, dislikeCount, category, ageLimit, tags, thumbnails, streamType, hlsUrl, dashMpdUrl, isShort, isUploaderVerified, privacy, uploaderSubscriberCount, subChannelName, subChannelUrl, subChannelAvatars, licence, supportInfo)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      id,
      url,
      name,
      uploaderName,
      uploaderUrl,
      uploaderAvatars,
      uploadDate,
      description,
      length,
      viewCount,
      likeCount,
      dislikeCount,
      category,
      ageLimit,
      tags,
      thumbnails,
      streamType,
      hlsUrl,
      dashMpdUrl,
      isShort,
      isUploaderVerified,
      privacy,
      uploaderSubscriberCount,
      subChannelName,
      subChannelUrl,
      subChannelAvatars,
      licence,
      supportInfo,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class AudioStreamDto (
  val url: String? = null,
  val averageBitrate: Long? = null,
  val formatName: String? = null,
  val formatSuffix: String? = null,
  val formatMimeType: String? = null,
  val audioTrackName: String? = null,
  val audioTrackLocale: String? = null,
  val audioTrackType: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): AudioStreamDto {
      val url = pigeonVar_list[0] as String?
      val averageBitrate = pigeonVar_list[1] as Long?
      val formatName = pigeonVar_list[2] as String?
      val formatSuffix = pigeonVar_list[3] as String?
      val formatMimeType = pigeonVar_list[4] as String?
      val audioTrackName = pigeonVar_list[5] as String?
      val audioTrackLocale = pigeonVar_list[6] as String?
      val audioTrackType = pigeonVar_list[7] as String?
      return AudioStreamDto(url, averageBitrate, formatName, formatSuffix, formatMimeType, audioTrackName, audioTrackLocale, audioTrackType)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      url,
      averageBitrate,
      formatName,
      formatSuffix,
      formatMimeType,
      audioTrackName,
      audioTrackLocale,
      audioTrackType,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class VideoStreamDto (
  val url: String? = null,
  val resolution: String? = null,
  val fps: Long? = null,
  val formatName: String? = null,
  val formatSuffix: String? = null,
  val formatMimeType: String? = null,
  val isVideoOnly: Boolean? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): VideoStreamDto {
      val url = pigeonVar_list[0] as String?
      val resolution = pigeonVar_list[1] as String?
      val fps = pigeonVar_list[2] as Long?
      val formatName = pigeonVar_list[3] as String?
      val formatSuffix = pigeonVar_list[4] as String?
      val formatMimeType = pigeonVar_list[5] as String?
      val isVideoOnly = pigeonVar_list[6] as Boolean?
      return VideoStreamDto(url, resolution, fps, formatName, formatSuffix, formatMimeType, isVideoOnly)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      url,
      resolution,
      fps,
      formatName,
      formatSuffix,
      formatMimeType,
      isVideoOnly,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class SubtitleStreamDto (
  val url: String? = null,
  val format: String? = null,
  val locale: String? = null,
  val isAutoGenerated: Boolean? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): SubtitleStreamDto {
      val url = pigeonVar_list[0] as String?
      val format = pigeonVar_list[1] as String?
      val locale = pigeonVar_list[2] as String?
      val isAutoGenerated = pigeonVar_list[3] as Boolean?
      return SubtitleStreamDto(url, format, locale, isAutoGenerated)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      url,
      format,
      locale,
      isAutoGenerated,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class StreamInfoItemDto (
  val url: String? = null,
  val id: String? = null,
  val name: String? = null,
  val uploaderName: String? = null,
  val uploaderUrl: String? = null,
  val uploaderAvatars: List<String?>? = null,
  val uploadDate: String? = null,
  val date: String? = null,
  val duration: Long? = null,
  val viewCount: Long? = null,
  val isShort: Boolean? = null,
  val thumbnails: List<String?>? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): StreamInfoItemDto {
      val url = pigeonVar_list[0] as String?
      val id = pigeonVar_list[1] as String?
      val name = pigeonVar_list[2] as String?
      val uploaderName = pigeonVar_list[3] as String?
      val uploaderUrl = pigeonVar_list[4] as String?
      val uploaderAvatars = pigeonVar_list[5] as List<String?>?
      val uploadDate = pigeonVar_list[6] as String?
      val date = pigeonVar_list[7] as String?
      val duration = pigeonVar_list[8] as Long?
      val viewCount = pigeonVar_list[9] as Long?
      val isShort = pigeonVar_list[10] as Boolean?
      val thumbnails = pigeonVar_list[11] as List<String?>?
      return StreamInfoItemDto(url, id, name, uploaderName, uploaderUrl, uploaderAvatars, uploadDate, date, duration, viewCount, isShort, thumbnails)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      url,
      id,
      name,
      uploaderName,
      uploaderUrl,
      uploaderAvatars,
      uploadDate,
      date,
      duration,
      viewCount,
      isShort,
      thumbnails,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class ChannelInfoItemDto (
  val url: String? = null,
  val name: String? = null,
  val description: String? = null,
  val thumbnails: List<String?>? = null,
  val subscriberCount: Long? = null,
  val streamCount: Long? = null,
  val isVerified: Boolean? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ChannelInfoItemDto {
      val url = pigeonVar_list[0] as String?
      val name = pigeonVar_list[1] as String?
      val description = pigeonVar_list[2] as String?
      val thumbnails = pigeonVar_list[3] as List<String?>?
      val subscriberCount = pigeonVar_list[4] as Long?
      val streamCount = pigeonVar_list[5] as Long?
      val isVerified = pigeonVar_list[6] as Boolean?
      return ChannelInfoItemDto(url, name, description, thumbnails, subscriberCount, streamCount, isVerified)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      url,
      name,
      description,
      thumbnails,
      subscriberCount,
      streamCount,
      isVerified,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class PlaylistInfoItemDto (
  val url: String? = null,
  val name: String? = null,
  val uploaderName: String? = null,
  val thumbnails: List<String?>? = null,
  val streamCount: Long? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PlaylistInfoItemDto {
      val url = pigeonVar_list[0] as String?
      val name = pigeonVar_list[1] as String?
      val uploaderName = pigeonVar_list[2] as String?
      val thumbnails = pigeonVar_list[3] as List<String?>?
      val streamCount = pigeonVar_list[4] as Long?
      return PlaylistInfoItemDto(url, name, uploaderName, thumbnails, streamCount)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      url,
      name,
      uploaderName,
      thumbnails,
      streamCount,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class ChannelDto (
  val id: String? = null,
  val name: String? = null,
  val url: String? = null,
  val avatars: List<String?>? = null,
  val banners: List<String?>? = null,
  val description: String? = null,
  val feedUrl: String? = null,
  val subscriberCount: Long? = null,
  val isVerified: Boolean? = null,
  val tabs: List<String?>? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ChannelDto {
      val id = pigeonVar_list[0] as String?
      val name = pigeonVar_list[1] as String?
      val url = pigeonVar_list[2] as String?
      val avatars = pigeonVar_list[3] as List<String?>?
      val banners = pigeonVar_list[4] as List<String?>?
      val description = pigeonVar_list[5] as String?
      val feedUrl = pigeonVar_list[6] as String?
      val subscriberCount = pigeonVar_list[7] as Long?
      val isVerified = pigeonVar_list[8] as Boolean?
      val tabs = pigeonVar_list[9] as List<String?>?
      return ChannelDto(id, name, url, avatars, banners, description, feedUrl, subscriberCount, isVerified, tabs)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      id,
      name,
      url,
      avatars,
      banners,
      description,
      feedUrl,
      subscriberCount,
      isVerified,
      tabs,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class PlaylistDto (
  val id: String? = null,
  val name: String? = null,
  val url: String? = null,
  val uploaderName: String? = null,
  val uploaderAvatars: List<String?>? = null,
  val uploaderUrl: String? = null,
  val banners: List<String?>? = null,
  val thumbnails: List<String?>? = null,
  val streamCount: Long? = null,
  val description: String? = null,
  val playlistType: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PlaylistDto {
      val id = pigeonVar_list[0] as String?
      val name = pigeonVar_list[1] as String?
      val url = pigeonVar_list[2] as String?
      val uploaderName = pigeonVar_list[3] as String?
      val uploaderAvatars = pigeonVar_list[4] as List<String?>?
      val uploaderUrl = pigeonVar_list[5] as String?
      val banners = pigeonVar_list[6] as List<String?>?
      val thumbnails = pigeonVar_list[7] as List<String?>?
      val streamCount = pigeonVar_list[8] as Long?
      val description = pigeonVar_list[9] as String?
      val playlistType = pigeonVar_list[10] as String?
      return PlaylistDto(id, name, url, uploaderName, uploaderAvatars, uploaderUrl, banners, thumbnails, streamCount, description, playlistType)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      id,
      name,
      url,
      uploaderName,
      uploaderAvatars,
      uploaderUrl,
      banners,
      thumbnails,
      streamCount,
      description,
      playlistType,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class CommentDto (
  val author: String? = null,
  val commentText: String? = null,
  val uploadDate: String? = null,
  val uploaderAvatars: List<String?>? = null,
  val uploaderUrl: String? = null,
  val commentId: String? = null,
  val likeCount: Long? = null,
  val hearted: Boolean? = null,
  val pinned: Boolean? = null,
  val replyCount: Long? = null,
  val isChannelOwner: Boolean? = null,
  val isUploaderVerified: Boolean? = null,
  val streamPosition: Long? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): CommentDto {
      val author = pigeonVar_list[0] as String?
      val commentText = pigeonVar_list[1] as String?
      val uploadDate = pigeonVar_list[2] as String?
      val uploaderAvatars = pigeonVar_list[3] as List<String?>?
      val uploaderUrl = pigeonVar_list[4] as String?
      val commentId = pigeonVar_list[5] as String?
      val likeCount = pigeonVar_list[6] as Long?
      val hearted = pigeonVar_list[7] as Boolean?
      val pinned = pigeonVar_list[8] as Boolean?
      val replyCount = pigeonVar_list[9] as Long?
      val isChannelOwner = pigeonVar_list[10] as Boolean?
      val isUploaderVerified = pigeonVar_list[11] as Boolean?
      val streamPosition = pigeonVar_list[12] as Long?
      return CommentDto(author, commentText, uploadDate, uploaderAvatars, uploaderUrl, commentId, likeCount, hearted, pinned, replyCount, isChannelOwner, isUploaderVerified, streamPosition)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      author,
      commentText,
      uploadDate,
      uploaderAvatars,
      uploaderUrl,
      commentId,
      likeCount,
      hearted,
      pinned,
      replyCount,
      isChannelOwner,
      isUploaderVerified,
      streamPosition,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class CommentsPageDto (
  val comments: List<CommentDto?>? = null,
  val hasNextPage: Boolean? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): CommentsPageDto {
      val comments = pigeonVar_list[0] as List<CommentDto?>?
      val hasNextPage = pigeonVar_list[1] as Boolean?
      return CommentsPageDto(comments, hasNextPage)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      comments,
      hasNextPage,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class SegmentDto (
  val url: String? = null,
  val title: String? = null,
  val previewUrl: String? = null,
  val startTimeSeconds: Long? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): SegmentDto {
      val url = pigeonVar_list[0] as String?
      val title = pigeonVar_list[1] as String?
      val previewUrl = pigeonVar_list[2] as String?
      val startTimeSeconds = pigeonVar_list[3] as Long?
      return SegmentDto(url, title, previewUrl, startTimeSeconds)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      url,
      title,
      previewUrl,
      startTimeSeconds,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class FramesetDto (
  val urls: List<String?>? = null,
  val width: Long? = null,
  val height: Long? = null,
  val totalCount: Long? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): FramesetDto {
      val urls = pigeonVar_list[0] as List<String?>?
      val width = pigeonVar_list[1] as Long?
      val height = pigeonVar_list[2] as Long?
      val totalCount = pigeonVar_list[3] as Long?
      return FramesetDto(urls, width, height, totalCount)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      urls,
      width,
      height,
      totalCount,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class StreamsDto (
  val audioStreams: List<AudioStreamDto?>? = null,
  val videoOnlyStreams: List<VideoStreamDto?>? = null,
  val videoStreams: List<VideoStreamDto?>? = null,
  val subtitleStreams: List<SubtitleStreamDto?>? = null,
  val segments: List<SegmentDto?>? = null,
  val framesets: List<FramesetDto?>? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): StreamsDto {
      val audioStreams = pigeonVar_list[0] as List<AudioStreamDto?>?
      val videoOnlyStreams = pigeonVar_list[1] as List<VideoStreamDto?>?
      val videoStreams = pigeonVar_list[2] as List<VideoStreamDto?>?
      val subtitleStreams = pigeonVar_list[3] as List<SubtitleStreamDto?>?
      val segments = pigeonVar_list[4] as List<SegmentDto?>?
      val framesets = pigeonVar_list[5] as List<FramesetDto?>?
      return StreamsDto(audioStreams, videoOnlyStreams, videoStreams, subtitleStreams, segments, framesets)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      audioStreams,
      videoOnlyStreams,
      videoStreams,
      subtitleStreams,
      segments,
      framesets,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class SearchResultDto (
  val videos: List<StreamInfoItemDto?>? = null,
  val playlists: List<PlaylistInfoItemDto?>? = null,
  val channels: List<ChannelInfoItemDto?>? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): SearchResultDto {
      val videos = pigeonVar_list[0] as List<StreamInfoItemDto?>?
      val playlists = pigeonVar_list[1] as List<PlaylistInfoItemDto?>?
      val channels = pigeonVar_list[2] as List<ChannelInfoItemDto?>?
      return SearchResultDto(videos, playlists, channels)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      videos,
      playlists,
      channels,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class TabPageDto (
  val streamItems: List<StreamInfoItemDto?>? = null,
  val playlistItems: List<PlaylistInfoItemDto?>? = null,
  val channelItems: List<ChannelInfoItemDto?>? = null,
  val hasNextPage: Boolean? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): TabPageDto {
      val streamItems = pigeonVar_list[0] as List<StreamInfoItemDto?>?
      val playlistItems = pigeonVar_list[1] as List<PlaylistInfoItemDto?>?
      val channelItems = pigeonVar_list[2] as List<ChannelInfoItemDto?>?
      val hasNextPage = pigeonVar_list[3] as Boolean?
      return TabPageDto(streamItems, playlistItems, channelItems, hasNextPage)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      streamItems,
      playlistItems,
      channelItems,
      hasNextPage,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class ServiceInfoDto (
  val serviceId: Long? = null,
  val name: String? = null,
  val baseUrl: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ServiceInfoDto {
      val serviceId = pigeonVar_list[0] as Long?
      val name = pigeonVar_list[1] as String?
      val baseUrl = pigeonVar_list[2] as String?
      return ServiceInfoDto(serviceId, name, baseUrl)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      serviceId,
      name,
      baseUrl,
    )
  }
}
private open class ExtractorApiPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          VideoInfoDto.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          AudioStreamDto.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          VideoStreamDto.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          SubtitleStreamDto.fromList(it)
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          StreamInfoItemDto.fromList(it)
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ChannelInfoItemDto.fromList(it)
        }
      }
      135.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PlaylistInfoItemDto.fromList(it)
        }
      }
      136.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ChannelDto.fromList(it)
        }
      }
      137.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PlaylistDto.fromList(it)
        }
      }
      138.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          CommentDto.fromList(it)
        }
      }
      139.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          CommentsPageDto.fromList(it)
        }
      }
      140.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          SegmentDto.fromList(it)
        }
      }
      141.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          FramesetDto.fromList(it)
        }
      }
      142.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          StreamsDto.fromList(it)
        }
      }
      143.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          SearchResultDto.fromList(it)
        }
      }
      144.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          TabPageDto.fromList(it)
        }
      }
      145.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ServiceInfoDto.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is VideoInfoDto -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is AudioStreamDto -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is VideoStreamDto -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is SubtitleStreamDto -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      is StreamInfoItemDto -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      is ChannelInfoItemDto -> {
        stream.write(134)
        writeValue(stream, value.toList())
      }
      is PlaylistInfoItemDto -> {
        stream.write(135)
        writeValue(stream, value.toList())
      }
      is ChannelDto -> {
        stream.write(136)
        writeValue(stream, value.toList())
      }
      is PlaylistDto -> {
        stream.write(137)
        writeValue(stream, value.toList())
      }
      is CommentDto -> {
        stream.write(138)
        writeValue(stream, value.toList())
      }
      is CommentsPageDto -> {
        stream.write(139)
        writeValue(stream, value.toList())
      }
      is SegmentDto -> {
        stream.write(140)
        writeValue(stream, value.toList())
      }
      is FramesetDto -> {
        stream.write(141)
        writeValue(stream, value.toList())
      }
      is StreamsDto -> {
        stream.write(142)
        writeValue(stream, value.toList())
      }
      is SearchResultDto -> {
        stream.write(143)
        writeValue(stream, value.toList())
      }
      is TabPageDto -> {
        stream.write(144)
        writeValue(stream, value.toList())
      }
      is ServiceInfoDto -> {
        stream.write(145)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface VideoExtractorApi {
  fun getVideoInfo(url: String, callback: (Result<VideoInfoDto>) -> Unit)
  fun getVideoStreams(url: String, callback: (Result<StreamsDto>) -> Unit)
  fun getVideoSegments(url: String, callback: (Result<List<SegmentDto?>>) -> Unit)
  fun getRelatedStreams(url: String, callback: (Result<SearchResultDto>) -> Unit)

  companion object {
    /** The codec used by VideoExtractorApi. */
    val codec: MessageCodec<Any?> by lazy {
      ExtractorApiPigeonCodec()
    }
    /** Sets up an instance of `VideoExtractorApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: VideoExtractorApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.newpipeextractor_dart.VideoExtractorApi.getVideoInfo$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val urlArg = args[0] as String
            api.getVideoInfo(urlArg) { result: Result<VideoInfoDto> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.newpipeextractor_dart.VideoExtractorApi.getVideoStreams$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val urlArg = args[0] as String
            api.getVideoStreams(urlArg) { result: Result<StreamsDto> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.newpipeextractor_dart.VideoExtractorApi.getVideoSegments$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val urlArg = args[0] as String
            api.getVideoSegments(urlArg) { result: Result<List<SegmentDto?>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.newpipeextractor_dart.VideoExtractorApi.getRelatedStreams$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val urlArg = args[0] as String
            api.getRelatedStreams(urlArg) { result: Result<SearchResultDto> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface SearchApi {
  fun searchYoutube(query: String, filters: List<String?>, callback: (Result<SearchResultDto>) -> Unit)
  fun getNextPage(callback: (Result<SearchResultDto>) -> Unit)
  fun searchYoutubeMusic(query: String, filters: List<String?>, callback: (Result<SearchResultDto>) -> Unit)
  fun getNextMusicPage(callback: (Result<SearchResultDto>) -> Unit)
  fun getSearchSuggestions(query: String, callback: (Result<List<String?>>) -> Unit)

  companion object {
    /** The codec used by SearchApi. */
    val codec: MessageCodec<Any?> by lazy {
      ExtractorApiPigeonCodec()
    }
    /** Sets up an instance of `SearchApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: SearchApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.newpipeextractor_dart.SearchApi.searchYoutube$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val queryArg = args[0] as String
            val filtersArg = args[1] as List<String?>
            api.searchYoutube(queryArg, filtersArg) { result: Result<SearchResultDto> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.newpipeextractor_dart.SearchApi.getNextPage$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.getNextPage{ result: Result<SearchResultDto> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.newpipeextractor_dart.SearchApi.searchYoutubeMusic$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val queryArg = args[0] as String
            val filtersArg = args[1] as List<String?>
            api.searchYoutubeMusic(queryArg, filtersArg) { result: Result<SearchResultDto> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.newpipeextractor_dart.SearchApi.getNextMusicPage$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.getNextMusicPage{ result: Result<SearchResultDto> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.newpipeextractor_dart.SearchApi.getSearchSuggestions$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val queryArg = args[0] as String
            api.getSearchSuggestions(queryArg) { result: Result<List<String?>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface ChannelApi {
  fun getChannelInfo(url: String, callback: (Result<ChannelDto>) -> Unit)
  fun getChannelUploads(url: String, callback: (Result<List<StreamInfoItemDto?>>) -> Unit)
  fun getChannelNextPage(callback: (Result<List<StreamInfoItemDto?>>) -> Unit)
  fun getChannelTabContent(url: String, tabFilter: String, callback: (Result<TabPageDto>) -> Unit)
  fun getChannelTabNextPage(callback: (Result<TabPageDto>) -> Unit)

  companion object {
    /** The codec used by ChannelApi. */
    val codec: MessageCodec<Any?> by lazy {
      ExtractorApiPigeonCodec()
    }
    /** Sets up an instance of `ChannelApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: ChannelApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.newpipeextractor_dart.ChannelApi.getChannelInfo$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val urlArg = args[0] as String
            api.getChannelInfo(urlArg) { result: Result<ChannelDto> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.newpipeextractor_dart.ChannelApi.getChannelUploads$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val urlArg = args[0] as String
            api.getChannelUploads(urlArg) { result: Result<List<StreamInfoItemDto?>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.newpipeextractor_dart.ChannelApi.getChannelNextPage$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.getChannelNextPage{ result: Result<List<StreamInfoItemDto?>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.newpipeextractor_dart.ChannelApi.getChannelTabContent$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val urlArg = args[0] as String
            val tabFilterArg = args[1] as String
            api.getChannelTabContent(urlArg, tabFilterArg) { result: Result<TabPageDto> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.newpipeextractor_dart.ChannelApi.getChannelTabNextPage$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.getChannelTabNextPage{ result: Result<TabPageDto> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface PlaylistApi {
  fun getPlaylistDetails(url: String, callback: (Result<PlaylistDto>) -> Unit)
  fun getPlaylistStreams(url: String, callback: (Result<List<StreamInfoItemDto?>>) -> Unit)
  fun getPlaylistNextPage(callback: (Result<List<StreamInfoItemDto?>>) -> Unit)

  companion object {
    /** The codec used by PlaylistApi. */
    val codec: MessageCodec<Any?> by lazy {
      ExtractorApiPigeonCodec()
    }
    /** Sets up an instance of `PlaylistApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: PlaylistApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.newpipeextractor_dart.PlaylistApi.getPlaylistDetails$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val urlArg = args[0] as String
            api.getPlaylistDetails(urlArg) { result: Result<PlaylistDto> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.newpipeextractor_dart.PlaylistApi.getPlaylistStreams$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val urlArg = args[0] as String
            api.getPlaylistStreams(urlArg) { result: Result<List<StreamInfoItemDto?>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.newpipeextractor_dart.PlaylistApi.getPlaylistNextPage$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.getPlaylistNextPage{ result: Result<List<StreamInfoItemDto?>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface CommentsApi {
  fun getComments(url: String, callback: (Result<CommentsPageDto>) -> Unit)
  fun getNextCommentsPage(callback: (Result<CommentsPageDto>) -> Unit)
  fun getCommentReplies(commentIndex: Long, callback: (Result<CommentsPageDto>) -> Unit)

  companion object {
    /** The codec used by CommentsApi. */
    val codec: MessageCodec<Any?> by lazy {
      ExtractorApiPigeonCodec()
    }
    /** Sets up an instance of `CommentsApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: CommentsApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.newpipeextractor_dart.CommentsApi.getComments$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val urlArg = args[0] as String
            api.getComments(urlArg) { result: Result<CommentsPageDto> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.newpipeextractor_dart.CommentsApi.getNextCommentsPage$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.getNextCommentsPage{ result: Result<CommentsPageDto> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.newpipeextractor_dart.CommentsApi.getCommentReplies$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val commentIndexArg = args[0] as Long
            api.getCommentReplies(commentIndexArg) { result: Result<CommentsPageDto> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface TrendingApi {
  fun getTrendingVideos(callback: (Result<List<StreamInfoItemDto?>>) -> Unit)
  fun listKiosks(callback: (Result<List<String?>>) -> Unit)
  fun getKioskContent(kioskId: String, callback: (Result<List<StreamInfoItemDto?>>) -> Unit)

  companion object {
    /** The codec used by TrendingApi. */
    val codec: MessageCodec<Any?> by lazy {
      ExtractorApiPigeonCodec()
    }
    /** Sets up an instance of `TrendingApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: TrendingApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.newpipeextractor_dart.TrendingApi.getTrendingVideos$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.getTrendingVideos{ result: Result<List<StreamInfoItemDto?>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.newpipeextractor_dart.TrendingApi.listKiosks$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.listKiosks{ result: Result<List<String?>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.newpipeextractor_dart.TrendingApi.getKioskContent$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val kioskIdArg = args[0] as String
            api.getKioskContent(kioskIdArg) { result: Result<List<StreamInfoItemDto?>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface UrlApi {
  fun getIdFromStreamUrl(url: String, callback: (Result<String?>) -> Unit)
  fun getIdFromPlaylistUrl(url: String, callback: (Result<String?>) -> Unit)
  fun getIdFromChannelUrl(url: String, callback: (Result<String?>) -> Unit)
  fun isValidStreamUrl(url: String, callback: (Result<Boolean>) -> Unit)
  fun isValidPlaylistUrl(url: String, callback: (Result<Boolean>) -> Unit)
  fun isValidChannelUrl(url: String, callback: (Result<Boolean>) -> Unit)

  companion object {
    /** The codec used by UrlApi. */
    val codec: MessageCodec<Any?> by lazy {
      ExtractorApiPigeonCodec()
    }
    /** Sets up an instance of `UrlApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: UrlApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.newpipeextractor_dart.UrlApi.getIdFromStreamUrl$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val urlArg = args[0] as String
            api.getIdFromStreamUrl(urlArg) { result: Result<String?> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.newpipeextractor_dart.UrlApi.getIdFromPlaylistUrl$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val urlArg = args[0] as String
            api.getIdFromPlaylistUrl(urlArg) { result: Result<String?> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.newpipeextractor_dart.UrlApi.getIdFromChannelUrl$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val urlArg = args[0] as String
            api.getIdFromChannelUrl(urlArg) { result: Result<String?> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.newpipeextractor_dart.UrlApi.isValidStreamUrl$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val urlArg = args[0] as String
            api.isValidStreamUrl(urlArg) { result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.newpipeextractor_dart.UrlApi.isValidPlaylistUrl$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val urlArg = args[0] as String
            api.isValidPlaylistUrl(urlArg) { result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.newpipeextractor_dart.UrlApi.isValidChannelUrl$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val urlArg = args[0] as String
            api.isValidChannelUrl(urlArg) { result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface CookieApi {
  fun setCookie(cookie: String, callback: (Result<Unit>) -> Unit)
  fun getCookieByUrl(url: String, callback: (Result<String?>) -> Unit)
  fun decodeCookie(cookie: String, callback: (Result<String?>) -> Unit)

  companion object {
    /** The codec used by CookieApi. */
    val codec: MessageCodec<Any?> by lazy {
      ExtractorApiPigeonCodec()
    }
    /** Sets up an instance of `CookieApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: CookieApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.newpipeextractor_dart.CookieApi.setCookie$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val cookieArg = args[0] as String
            api.setCookie(cookieArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.newpipeextractor_dart.CookieApi.getCookieByUrl$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val urlArg = args[0] as String
            api.getCookieByUrl(urlArg) { result: Result<String?> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.newpipeextractor_dart.CookieApi.decodeCookie$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val cookieArg = args[0] as String
            api.decodeCookie(cookieArg) { result: Result<String?> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface LocalizationApi {
  fun setLocalization(languageCode: String, countryCode: String, callback: (Result<Unit>) -> Unit)

  companion object {
    /** The codec used by LocalizationApi. */
    val codec: MessageCodec<Any?> by lazy {
      ExtractorApiPigeonCodec()
    }
    /** Sets up an instance of `LocalizationApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: LocalizationApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.newpipeextractor_dart.LocalizationApi.setLocalization$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val languageCodeArg = args[0] as String
            val countryCodeArg = args[1] as String
            api.setLocalization(languageCodeArg, countryCodeArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface ServiceApi {
  fun getAvailableServices(callback: (Result<List<ServiceInfoDto?>>) -> Unit)

  companion object {
    /** The codec used by ServiceApi. */
    val codec: MessageCodec<Any?> by lazy {
      ExtractorApiPigeonCodec()
    }
    /** Sets up an instance of `ServiceApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: ServiceApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.newpipeextractor_dart.ServiceApi.getAvailableServices$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.getAvailableServices{ result: Result<List<ServiceInfoDto?>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface ServiceStreamApi {
  fun getStreamInfo(serviceId: Long, url: String, callback: (Result<VideoInfoDto>) -> Unit)
  fun getStreams(serviceId: Long, url: String, callback: (Result<StreamsDto>) -> Unit)
  fun getRelatedItems(serviceId: Long, url: String, callback: (Result<SearchResultDto>) -> Unit)

  companion object {
    /** The codec used by ServiceStreamApi. */
    val codec: MessageCodec<Any?> by lazy {
      ExtractorApiPigeonCodec()
    }
    /** Sets up an instance of `ServiceStreamApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: ServiceStreamApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.newpipeextractor_dart.ServiceStreamApi.getStreamInfo$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val serviceIdArg = args[0] as Long
            val urlArg = args[1] as String
            api.getStreamInfo(serviceIdArg, urlArg) { result: Result<VideoInfoDto> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.newpipeextractor_dart.ServiceStreamApi.getStreams$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val serviceIdArg = args[0] as Long
            val urlArg = args[1] as String
            api.getStreams(serviceIdArg, urlArg) { result: Result<StreamsDto> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.newpipeextractor_dart.ServiceStreamApi.getRelatedItems$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val serviceIdArg = args[0] as Long
            val urlArg = args[1] as String
            api.getRelatedItems(serviceIdArg, urlArg) { result: Result<SearchResultDto> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface ServiceSearchApi {
  fun search(serviceId: Long, query: String, filters: List<String?>, callback: (Result<SearchResultDto>) -> Unit)
  fun searchNextPage(serviceId: Long, callback: (Result<SearchResultDto>) -> Unit)
  fun getSuggestions(serviceId: Long, query: String, callback: (Result<List<String?>>) -> Unit)

  companion object {
    /** The codec used by ServiceSearchApi. */
    val codec: MessageCodec<Any?> by lazy {
      ExtractorApiPigeonCodec()
    }
    /** Sets up an instance of `ServiceSearchApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: ServiceSearchApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.newpipeextractor_dart.ServiceSearchApi.search$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val serviceIdArg = args[0] as Long
            val queryArg = args[1] as String
            val filtersArg = args[2] as List<String?>
            api.search(serviceIdArg, queryArg, filtersArg) { result: Result<SearchResultDto> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.newpipeextractor_dart.ServiceSearchApi.searchNextPage$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val serviceIdArg = args[0] as Long
            api.searchNextPage(serviceIdArg) { result: Result<SearchResultDto> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.newpipeextractor_dart.ServiceSearchApi.getSuggestions$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val serviceIdArg = args[0] as Long
            val queryArg = args[1] as String
            api.getSuggestions(serviceIdArg, queryArg) { result: Result<List<String?>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface ServiceChannelApi {
  fun getChannelInfo(serviceId: Long, url: String, callback: (Result<ChannelDto>) -> Unit)
  fun getChannelContent(serviceId: Long, url: String, callback: (Result<List<StreamInfoItemDto?>>) -> Unit)
  fun getChannelContentNextPage(serviceId: Long, callback: (Result<List<StreamInfoItemDto?>>) -> Unit)

  companion object {
    /** The codec used by ServiceChannelApi. */
    val codec: MessageCodec<Any?> by lazy {
      ExtractorApiPigeonCodec()
    }
    /** Sets up an instance of `ServiceChannelApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: ServiceChannelApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.newpipeextractor_dart.ServiceChannelApi.getChannelInfo$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val serviceIdArg = args[0] as Long
            val urlArg = args[1] as String
            api.getChannelInfo(serviceIdArg, urlArg) { result: Result<ChannelDto> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.newpipeextractor_dart.ServiceChannelApi.getChannelContent$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val serviceIdArg = args[0] as Long
            val urlArg = args[1] as String
            api.getChannelContent(serviceIdArg, urlArg) { result: Result<List<StreamInfoItemDto?>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.newpipeextractor_dart.ServiceChannelApi.getChannelContentNextPage$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val serviceIdArg = args[0] as Long
            api.getChannelContentNextPage(serviceIdArg) { result: Result<List<StreamInfoItemDto?>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface ServicePlaylistApi {
  fun getPlaylistInfo(serviceId: Long, url: String, callback: (Result<PlaylistDto>) -> Unit)
  fun getPlaylistContent(serviceId: Long, url: String, callback: (Result<List<StreamInfoItemDto?>>) -> Unit)
  fun getPlaylistContentNextPage(serviceId: Long, callback: (Result<List<StreamInfoItemDto?>>) -> Unit)

  companion object {
    /** The codec used by ServicePlaylistApi. */
    val codec: MessageCodec<Any?> by lazy {
      ExtractorApiPigeonCodec()
    }
    /** Sets up an instance of `ServicePlaylistApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: ServicePlaylistApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.newpipeextractor_dart.ServicePlaylistApi.getPlaylistInfo$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val serviceIdArg = args[0] as Long
            val urlArg = args[1] as String
            api.getPlaylistInfo(serviceIdArg, urlArg) { result: Result<PlaylistDto> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.newpipeextractor_dart.ServicePlaylistApi.getPlaylistContent$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val serviceIdArg = args[0] as Long
            val urlArg = args[1] as String
            api.getPlaylistContent(serviceIdArg, urlArg) { result: Result<List<StreamInfoItemDto?>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.newpipeextractor_dart.ServicePlaylistApi.getPlaylistContentNextPage$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val serviceIdArg = args[0] as Long
            api.getPlaylistContentNextPage(serviceIdArg) { result: Result<List<StreamInfoItemDto?>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface ServiceKioskApi {
  fun listServiceKiosks(serviceId: Long, callback: (Result<List<String?>>) -> Unit)
  fun getServiceKioskContent(serviceId: Long, kioskId: String, callback: (Result<List<StreamInfoItemDto?>>) -> Unit)

  companion object {
    /** The codec used by ServiceKioskApi. */
    val codec: MessageCodec<Any?> by lazy {
      ExtractorApiPigeonCodec()
    }
    /** Sets up an instance of `ServiceKioskApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: ServiceKioskApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.newpipeextractor_dart.ServiceKioskApi.listServiceKiosks$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val serviceIdArg = args[0] as Long
            api.listServiceKiosks(serviceIdArg) { result: Result<List<String?>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.newpipeextractor_dart.ServiceKioskApi.getServiceKioskContent$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val serviceIdArg = args[0] as Long
            val kioskIdArg = args[1] as String
            api.getServiceKioskContent(serviceIdArg, kioskIdArg) { result: Result<List<StreamInfoItemDto?>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
