package com.ottomancoder.newpipeextractor_dart

import org.schabi.newpipe.extractor.Image
import org.schabi.newpipe.extractor.InfoItem
import org.schabi.newpipe.extractor.channel.ChannelInfoItem
import org.schabi.newpipe.extractor.playlist.PlaylistInfoItem
import org.schabi.newpipe.extractor.services.youtube.linkHandler.YoutubeChannelLinkHandlerFactory
import org.schabi.newpipe.extractor.services.youtube.linkHandler.YoutubePlaylistLinkHandlerFactory
import org.schabi.newpipe.extractor.services.youtube.linkHandler.YoutubeStreamLinkHandlerFactory
import org.schabi.newpipe.extractor.stream.AudioStream
import org.schabi.newpipe.extractor.stream.Frameset
import org.schabi.newpipe.extractor.stream.StreamExtractor
import org.schabi.newpipe.extractor.stream.StreamInfoItem
import org.schabi.newpipe.extractor.stream.StreamSegment
import org.schabi.newpipe.extractor.stream.SubtitlesStream
import org.schabi.newpipe.extractor.stream.VideoStream
import java.time.format.DateTimeFormatter

object ExtractorHelper {

    fun imagesToList(images: List<Image>): List<String?> {
        return images.map { it.url }
    }

    fun mapVideoInfo(extractor: StreamExtractor): VideoInfoDto {
        return VideoInfoDto(
            id = tryOrNull { extractor.id },
            url = tryOrNull { extractor.url },
            name = tryOrNull { extractor.name },
            uploaderName = tryOrNull { extractor.uploaderName },
            uploaderUrl = tryOrNull { extractor.uploaderUrl },
            uploaderAvatars = tryOrNull { imagesToList(extractor.uploaderAvatars) },
            uploadDate = tryOrNull { extractor.textualUploadDate },
            description = tryOrNull { extractor.description?.content },
            length = tryOrNull { extractor.length },
            viewCount = tryOrNull { extractor.viewCount },
            likeCount = tryOrNull { extractor.likeCount },
            dislikeCount = tryOrNull { extractor.dislikeCount },
            category = tryOrNull { extractor.category },
            ageLimit = tryOrNull { extractor.ageLimit.toLong() },
            tags = tryOrNull { extractor.tags.toList() },
            thumbnails = tryOrNull { imagesToList(extractor.thumbnails) },
            streamType = tryOrNull { extractor.streamType?.name },
            hlsUrl = tryOrNull { extractor.hlsUrl },
            dashMpdUrl = tryOrNull { extractor.dashMpdUrl },
            isShort = tryOrNull { extractor.isShortFormContent },
            isUploaderVerified = tryOrNull { extractor.isUploaderVerified },
            privacy = tryOrNull { extractor.privacy?.name }
        )
    }

    fun mapAudioStream(stream: AudioStream): AudioStreamDto {
        return AudioStreamDto(
            url = tryOrNull { stream.content },
            averageBitrate = tryOrNull { stream.averageBitrate.toLong() },
            formatName = tryOrNull { stream.format?.name },
            formatSuffix = tryOrNull { stream.format?.suffix },
            formatMimeType = tryOrNull { stream.format?.mimeType },
            audioTrackName = tryOrNull { stream.audioTrackName },
            audioTrackLocale = tryOrNull { stream.audioLocale?.language },
            audioTrackType = tryOrNull { stream.audioTrackType?.name }
        )
    }

    fun mapVideoStream(stream: VideoStream): VideoStreamDto {
        return VideoStreamDto(
            url = tryOrNull { stream.content },
            resolution = tryOrNull { stream.resolution },
            fps = tryOrNull { stream.fps.toLong() },
            formatName = tryOrNull { stream.format?.name },
            formatSuffix = tryOrNull { stream.format?.suffix },
            formatMimeType = tryOrNull { stream.format?.mimeType },
            isVideoOnly = tryOrNull { stream.isVideoOnly }
        )
    }

    fun mapSubtitleStream(stream: SubtitlesStream): SubtitleStreamDto {
        return SubtitleStreamDto(
            url = tryOrNull { stream.content },
            format = tryOrNull { stream.format?.name },
            locale = tryOrNull { stream.locale?.language },
            isAutoGenerated = tryOrNull { stream.isAutoGenerated }
        )
    }

    fun mapStreamInfoItem(item: StreamInfoItem): StreamInfoItemDto {
        return StreamInfoItemDto(
            url = tryOrNull { item.url },
            id = tryOrNull { getIdFromStreamUrl(item.url) },
            name = tryOrNull { item.name },
            uploaderName = tryOrNull { item.uploaderName },
            uploaderUrl = tryOrNull { item.uploaderUrl },
            uploaderAvatars = tryOrNull { imagesToList(item.uploaderAvatars) },
            uploadDate = tryOrNull { item.textualUploadDate },
            date = tryOrNull {
                item.uploadDate?.offsetDateTime()?.format(DateTimeFormatter.ISO_DATE_TIME)
            },
            duration = tryOrNull { item.duration },
            viewCount = tryOrNull { item.viewCount },
            isShort = tryOrNull { item.isShortFormContent }
        )
    }

    fun mapChannelInfoItem(item: ChannelInfoItem): ChannelInfoItemDto {
        return ChannelInfoItemDto(
            url = tryOrNull { item.url },
            name = tryOrNull { item.name },
            description = tryOrNull { item.description },
            thumbnails = tryOrNull { imagesToList(item.thumbnails) },
            subscriberCount = tryOrNull { item.subscriberCount },
            streamCount = tryOrNull { item.streamCount },
            isVerified = tryOrNull { item.isVerified }
        )
    }

    fun mapPlaylistInfoItem(item: PlaylistInfoItem): PlaylistInfoItemDto {
        return PlaylistInfoItemDto(
            url = tryOrNull { item.url },
            name = tryOrNull { item.name },
            uploaderName = tryOrNull { item.uploaderName },
            thumbnails = tryOrNull { imagesToList(item.thumbnails) },
            streamCount = tryOrNull { item.streamCount }
        )
    }

    fun mapSegment(segment: StreamSegment): SegmentDto {
        return SegmentDto(
            url = tryOrNull { segment.url },
            title = tryOrNull { segment.title },
            previewUrl = tryOrNull { segment.previewUrl },
            startTimeSeconds = tryOrNull { segment.startTimeSeconds.toLong() }
        )
    }

    fun mapFrameset(frameset: Frameset): FramesetDto {
        return FramesetDto(
            urls = tryOrNull { frameset.urls },
            width = tryOrNull { frameset.frameWidth.toLong() },
            height = tryOrNull { frameset.frameHeight.toLong() },
            totalCount = tryOrNull { frameset.totalCount.toLong() }
        )
    }

    fun categorizeInfoItems(items: List<InfoItem>): SearchResultDto {
        val videos = mutableListOf<StreamInfoItemDto?>()
        val playlists = mutableListOf<PlaylistInfoItemDto?>()
        val channels = mutableListOf<ChannelInfoItemDto?>()

        for (item in items) {
            when (item.infoType) {
                InfoItem.InfoType.STREAM -> videos.add(mapStreamInfoItem(item as StreamInfoItem))
                InfoItem.InfoType.CHANNEL -> channels.add(mapChannelInfoItem(item as ChannelInfoItem))
                InfoItem.InfoType.PLAYLIST -> playlists.add(mapPlaylistInfoItem(item as PlaylistInfoItem))
                else -> { /* ignore */ }
            }
        }

        return SearchResultDto(
            videos = videos,
            playlists = playlists,
            channels = channels
        )
    }

    fun getIdFromStreamUrl(url: String): String? {
        return try {
            YoutubeStreamLinkHandlerFactory.getInstance().fromUrl(url).id
        } catch (e: Exception) {
            null
        }
    }

    fun getIdFromPlaylistUrl(url: String): String? {
        return try {
            YoutubePlaylistLinkHandlerFactory.getInstance().fromUrl(url).id
        } catch (e: Exception) {
            null
        }
    }

    fun getIdFromChannelUrl(url: String): String? {
        return try {
            YoutubeChannelLinkHandlerFactory.getInstance().fromUrl(url).id
        } catch (e: Exception) {
            null
        }
    }

    inline fun <T> tryOrNull(block: () -> T): T? {
        return try {
            block()
        } catch (e: Exception) {
            null
        }
    }
}
