// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'subtitle_stream.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_$SubtitleStreamImpl _$$SubtitleStreamImplFromJson(Map<String, dynamic> json) =>
    _$SubtitleStreamImpl(
      url: json['url'] as String?,
      format: json['format'] as String?,
      languageCode: json['languageCode'] as String?,
      isAutoGenerated: json['isAutoGenerated'] as bool? ?? false,
    );

Map<String, dynamic> _$$SubtitleStreamImplToJson(
        _$SubtitleStreamImpl instance) =>
    <String, dynamic>{
      'url': instance.url,
      'format': instance.format,
      'languageCode': instance.languageCode,
      'isAutoGenerated': instance.isAutoGenerated,
    };
