// coverage:ignore-file
// GENERATED CODE - DO NOT MODIFY BY HAND
// ignore_for_file: type=lint
// ignore_for_file: unused_element, deprecated_member_use, deprecated_member_use_from_same_package, use_function_type_syntax_for_parameters, unnecessary_const, avoid_init_to_null, invalid_override_different_default_values_named, prefer_expression_function_bodies, annotate_overrides, invalid_annotation_target, unnecessary_question_mark

part of 'subtitle_stream.dart';

// **************************************************************************
// FreezedGenerator
// **************************************************************************

T _$identity<T>(T value) => value;

final _privateConstructorUsedError = UnsupportedError(
    'It seems like you constructed your class using `MyClass._()`. This constructor is only meant to be used by freezed and you are not supposed to need it nor use it.\nPlease check the documentation here for more information: https://github.com/rrousselGit/freezed#adding-getters-and-methods-to-our-models');

SubtitleStream _$SubtitleStreamFromJson(Map<String, dynamic> json) {
  return _SubtitleStream.fromJson(json);
}

/// @nodoc
mixin _$SubtitleStream {
  String? get url => throw _privateConstructorUsedError;
  String? get format => throw _privateConstructorUsedError;
  String? get languageCode => throw _privateConstructorUsedError;
  bool get isAutoGenerated => throw _privateConstructorUsedError;

  /// Serializes this SubtitleStream to a JSON map.
  Map<String, dynamic> toJson() => throw _privateConstructorUsedError;

  /// Create a copy of SubtitleStream
  /// with the given fields replaced by the non-null parameter values.
  @JsonKey(includeFromJson: false, includeToJson: false)
  $SubtitleStreamCopyWith<SubtitleStream> get copyWith =>
      throw _privateConstructorUsedError;
}

/// @nodoc
abstract class $SubtitleStreamCopyWith<$Res> {
  factory $SubtitleStreamCopyWith(
          SubtitleStream value, $Res Function(SubtitleStream) then) =
      _$SubtitleStreamCopyWithImpl<$Res, SubtitleStream>;
  @useResult
  $Res call(
      {String? url,
      String? format,
      String? languageCode,
      bool isAutoGenerated});
}

/// @nodoc
class _$SubtitleStreamCopyWithImpl<$Res, $Val extends SubtitleStream>
    implements $SubtitleStreamCopyWith<$Res> {
  _$SubtitleStreamCopyWithImpl(this._value, this._then);

  // ignore: unused_field
  final $Val _value;
  // ignore: unused_field
  final $Res Function($Val) _then;

  /// Create a copy of SubtitleStream
  /// with the given fields replaced by the non-null parameter values.
  @pragma('vm:prefer-inline')
  @override
  $Res call({
    Object? url = freezed,
    Object? format = freezed,
    Object? languageCode = freezed,
    Object? isAutoGenerated = null,
  }) {
    return _then(_value.copyWith(
      url: freezed == url
          ? _value.url
          : url // ignore: cast_nullable_to_non_nullable
              as String?,
      format: freezed == format
          ? _value.format
          : format // ignore: cast_nullable_to_non_nullable
              as String?,
      languageCode: freezed == languageCode
          ? _value.languageCode
          : languageCode // ignore: cast_nullable_to_non_nullable
              as String?,
      isAutoGenerated: null == isAutoGenerated
          ? _value.isAutoGenerated
          : isAutoGenerated // ignore: cast_nullable_to_non_nullable
              as bool,
    ) as $Val);
  }
}

/// @nodoc
abstract class _$$SubtitleStreamImplCopyWith<$Res>
    implements $SubtitleStreamCopyWith<$Res> {
  factory _$$SubtitleStreamImplCopyWith(_$SubtitleStreamImpl value,
          $Res Function(_$SubtitleStreamImpl) then) =
      __$$SubtitleStreamImplCopyWithImpl<$Res>;
  @override
  @useResult
  $Res call(
      {String? url,
      String? format,
      String? languageCode,
      bool isAutoGenerated});
}

/// @nodoc
class __$$SubtitleStreamImplCopyWithImpl<$Res>
    extends _$SubtitleStreamCopyWithImpl<$Res, _$SubtitleStreamImpl>
    implements _$$SubtitleStreamImplCopyWith<$Res> {
  __$$SubtitleStreamImplCopyWithImpl(
      _$SubtitleStreamImpl _value, $Res Function(_$SubtitleStreamImpl) _then)
      : super(_value, _then);

  /// Create a copy of SubtitleStream
  /// with the given fields replaced by the non-null parameter values.
  @pragma('vm:prefer-inline')
  @override
  $Res call({
    Object? url = freezed,
    Object? format = freezed,
    Object? languageCode = freezed,
    Object? isAutoGenerated = null,
  }) {
    return _then(_$SubtitleStreamImpl(
      url: freezed == url
          ? _value.url
          : url // ignore: cast_nullable_to_non_nullable
              as String?,
      format: freezed == format
          ? _value.format
          : format // ignore: cast_nullable_to_non_nullable
              as String?,
      languageCode: freezed == languageCode
          ? _value.languageCode
          : languageCode // ignore: cast_nullable_to_non_nullable
              as String?,
      isAutoGenerated: null == isAutoGenerated
          ? _value.isAutoGenerated
          : isAutoGenerated // ignore: cast_nullable_to_non_nullable
              as bool,
    ));
  }
}

/// @nodoc
@JsonSerializable()
class _$SubtitleStreamImpl implements _SubtitleStream {
  const _$SubtitleStreamImpl(
      {this.url, this.format, this.languageCode, this.isAutoGenerated = false});

  factory _$SubtitleStreamImpl.fromJson(Map<String, dynamic> json) =>
      _$$SubtitleStreamImplFromJson(json);

  @override
  final String? url;
  @override
  final String? format;
  @override
  final String? languageCode;
  @override
  @JsonKey()
  final bool isAutoGenerated;

  @override
  String toString() {
    return 'SubtitleStream(url: $url, format: $format, languageCode: $languageCode, isAutoGenerated: $isAutoGenerated)';
  }

  @override
  bool operator ==(Object other) {
    return identical(this, other) ||
        (other.runtimeType == runtimeType &&
            other is _$SubtitleStreamImpl &&
            (identical(other.url, url) || other.url == url) &&
            (identical(other.format, format) || other.format == format) &&
            (identical(other.languageCode, languageCode) ||
                other.languageCode == languageCode) &&
            (identical(other.isAutoGenerated, isAutoGenerated) ||
                other.isAutoGenerated == isAutoGenerated));
  }

  @JsonKey(includeFromJson: false, includeToJson: false)
  @override
  int get hashCode =>
      Object.hash(runtimeType, url, format, languageCode, isAutoGenerated);

  /// Create a copy of SubtitleStream
  /// with the given fields replaced by the non-null parameter values.
  @JsonKey(includeFromJson: false, includeToJson: false)
  @override
  @pragma('vm:prefer-inline')
  _$$SubtitleStreamImplCopyWith<_$SubtitleStreamImpl> get copyWith =>
      __$$SubtitleStreamImplCopyWithImpl<_$SubtitleStreamImpl>(
          this, _$identity);

  @override
  Map<String, dynamic> toJson() {
    return _$$SubtitleStreamImplToJson(
      this,
    );
  }
}

abstract class _SubtitleStream implements SubtitleStream {
  const factory _SubtitleStream(
      {final String? url,
      final String? format,
      final String? languageCode,
      final bool isAutoGenerated}) = _$SubtitleStreamImpl;

  factory _SubtitleStream.fromJson(Map<String, dynamic> json) =
      _$SubtitleStreamImpl.fromJson;

  @override
  String? get url;
  @override
  String? get format;
  @override
  String? get languageCode;
  @override
  bool get isAutoGenerated;

  /// Create a copy of SubtitleStream
  /// with the given fields replaced by the non-null parameter values.
  @override
  @JsonKey(includeFromJson: false, includeToJson: false)
  _$$SubtitleStreamImplCopyWith<_$SubtitleStreamImpl> get copyWith =>
      throw _privateConstructorUsedError;
}
