import 'package:freezed_annotation/freezed_annotation.dart';
part 'subtitle_stream.freezed.dart';
part 'subtitle_stream.g.dart';

/// Subtitle/caption track with language, format, and auto-generation flag.
@freezed
class SubtitleStream with _$SubtitleStream {
  const factory SubtitleStream({
    String? url,
    String? format,
    String? languageCode,
    @Default(false) bool isAutoGenerated,
  }) = _SubtitleStream;

  factory SubtitleStream.fromJson(Map<String, dynamic> json) =>
      _$SubtitleStreamFromJson(json);
}
