group 'com.ottomancoder.newpipeextractor_dart'
version '1.0'

buildscript {
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:8.1.0'
    }
}

apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'

allprojects {
    repositories {
        google()
        mavenCentral()
        maven { url "https://jitpack.io" }
    }
}

android {

    namespace 'com.ottomancoder.newpipeextractor_dart'
    compileSdk 35

    defaultConfig {
        minSdk 22
        multiDexEnabled true
    }

    compileOptions {
        coreLibraryDesugaringEnabled true
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = '1.8'
    }

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    dependencies {
        coreLibraryDesugaring 'com.android.tools:desugar_jdk_libs:2.1.4'
        implementation 'androidx.annotation:annotation:1.1.0'
        implementation 'androidx.preference:preference:1.2.1'
        implementation 'com.github.teamnewpipe:NewPipeExtractor:v0.26.2'
        implementation 'org.jsoup:jsoup:1.13.1'
        implementation 'org.mozilla:rhino:1.7.12'
        implementation ('com.github.spotbugs:spotbugs-annotations:4.8.3')
        implementation 'org.nibor.autolink:autolink:0.10.0'
        implementation "com.squareup.okhttp3:okhttp:4.12.0"
        implementation 'com.google.code.gson:gson:2.11.0'
    }
}
