import 'package:newpipeextractor_dart/src/generated/extractor_api.g.dart';
import 'package:newpipeextractor_dart/src/models/enums.dart';
import 'package:newpipeextractor_dart/src/models/service_info.dart';
import 'package:newpipeextractor_dart/src/models/video_info.dart';
import 'package:newpipeextractor_dart/src/models/youtube_video.dart';
import 'package:newpipeextractor_dart/src/models/youtube_channel.dart';
import 'package:newpipeextractor_dart/src/models/youtube_comment.dart';
import 'package:newpipeextractor_dart/src/models/youtube_playlist.dart';
import 'package:newpipeextractor_dart/src/models/search_result.dart';
import 'package:newpipeextractor_dart/src/models/comments_page.dart';
import 'package:newpipeextractor_dart/src/models/stream_info_item.dart';
import 'package:newpipeextractor_dart/src/models/channel_info_item.dart';
import 'package:newpipeextractor_dart/src/models/playlist_info_item.dart';
import 'package:newpipeextractor_dart/src/models/stream_segment.dart';
import 'package:newpipeextractor_dart/src/models/frameset.dart';
import 'package:newpipeextractor_dart/src/models/streams/audio_only_stream.dart';
import 'package:newpipeextractor_dart/src/models/streams/video_only_stream.dart';
import 'package:newpipeextractor_dart/src/models/streams/video_stream.dart';
import 'package:newpipeextractor_dart/src/models/streams/subtitle_stream.dart';

ServiceInfo mapServiceInfo(ServiceInfoDto d) => ServiceInfo(
  serviceId: d.serviceId ?? 0,
  name: d.name ?? 'Unknown',
  baseUrl: d.baseUrl,
);

VideoInfo mapVideoInfo(VideoInfoDto d) => VideoInfo(
  id: d.id, url: d.url, name: d.name,
  uploaderName: d.uploaderName, uploaderUrl: d.uploaderUrl,
  uploaderAvatars: d.uploaderAvatars?.whereType<String>().toList() ?? [],
  uploadDate: d.uploadDate, description: d.description,
  length: d.length, viewCount: d.viewCount,
  likeCount: d.likeCount, dislikeCount: d.dislikeCount,
  category: d.category, ageLimit: d.ageLimit,
  tags: d.tags?.whereType<String>().toList() ?? [],
  thumbnails: d.thumbnails?.whereType<String>().toList() ?? [],
  streamType: StreamType.fromString(d.streamType),
  hlsUrl: d.hlsUrl, dashMpdUrl: d.dashMpdUrl,
  isShort: d.isShort ?? false,
  isUploaderVerified: d.isUploaderVerified ?? false,
  privacy: Privacy.fromString(d.privacy),
  uploaderSubscriberCount: d.uploaderSubscriberCount,
  subChannelName: d.subChannelName,
  subChannelUrl: d.subChannelUrl,
  subChannelAvatars: d.subChannelAvatars?.whereType<String>().toList() ?? [],
  licence: d.licence,
  supportInfo: d.supportInfo,
);

AudioOnlyStream mapAudio(AudioStreamDto d) => AudioOnlyStream(
  url: d.url, averageBitrate: d.averageBitrate ?? 0,
  formatName: d.formatName, formatSuffix: d.formatSuffix,
  formatMimeType: d.formatMimeType,
  audioTrackName: d.audioTrackName, audioTrackLocale: d.audioTrackLocale,
  audioTrackType: d.audioTrackType,
);

VideoOnlyStream mapVideoOnly(VideoStreamDto d) => VideoOnlyStream(
  url: d.url, resolution: d.resolution, fps: d.fps ?? 0,
  formatName: d.formatName, formatSuffix: d.formatSuffix,
  formatMimeType: d.formatMimeType,
);

VideoStream mapVideo(VideoStreamDto d) => VideoStream(
  url: d.url, resolution: d.resolution, fps: d.fps ?? 0,
  formatName: d.formatName, formatSuffix: d.formatSuffix,
  formatMimeType: d.formatMimeType,
);

SubtitleStream mapSubtitle(SubtitleStreamDto d) => SubtitleStream(
  url: d.url, format: d.format, languageCode: d.locale,
  isAutoGenerated: d.isAutoGenerated ?? false,
);

StreamInfoItem mapStreamInfoItem(StreamInfoItemDto d) => StreamInfoItem(
  url: d.url, id: d.id, name: d.name,
  uploaderName: d.uploaderName, uploaderUrl: d.uploaderUrl,
  uploaderAvatars: d.uploaderAvatars?.whereType<String>().toList() ?? [],
  uploadDate: d.uploadDate, date: d.date,
  duration: d.duration, viewCount: d.viewCount,
  isShort: d.isShort ?? false,
  thumbnails: d.thumbnails?.whereType<String>().toList() ?? [],
);

ChannelInfoItem mapChannelInfoItem(ChannelInfoItemDto d) => ChannelInfoItem(
  url: d.url, name: d.name, description: d.description,
  thumbnails: d.thumbnails?.whereType<String>().toList() ?? [],
  subscriberCount: d.subscriberCount, streamCount: d.streamCount ?? 0,
  isVerified: d.isVerified ?? false,
);

PlaylistInfoItem mapPlaylistInfoItem(PlaylistInfoItemDto d) => PlaylistInfoItem(
  url: d.url, name: d.name, uploaderName: d.uploaderName,
  thumbnails: d.thumbnails?.whereType<String>().toList() ?? [],
  streamCount: d.streamCount ?? 0,
);

StreamSegment mapSegment(SegmentDto d) => StreamSegment(
  url: d.url, title: d.title, previewUrl: d.previewUrl,
  startTimeSeconds: d.startTimeSeconds ?? 0,
);

Frameset mapFrameset(FramesetDto d) => Frameset(
  urls: d.urls?.whereType<String>().toList() ?? [],
  width: d.width ?? 0, height: d.height ?? 0,
  totalCount: d.totalCount ?? 0,
);

SearchResult mapSearchResult(SearchResultDto d) => SearchResult(
  videos: d.videos?.whereType<StreamInfoItemDto>().map(mapStreamInfoItem).toList() ?? [],
  playlists: d.playlists?.whereType<PlaylistInfoItemDto>().map(mapPlaylistInfoItem).toList() ?? [],
  channels: d.channels?.whereType<ChannelInfoItemDto>().map(mapChannelInfoItem).toList() ?? [],
);

YoutubeChannel mapChannel(ChannelDto d) => YoutubeChannel(
  id: d.id, name: d.name, url: d.url,
  avatars: d.avatars?.whereType<String>().toList() ?? [],
  banners: d.banners?.whereType<String>().toList() ?? [],
  description: d.description, feedUrl: d.feedUrl,
  subscriberCount: d.subscriberCount,
  isVerified: d.isVerified ?? false,
  tabs: d.tabs?.whereType<String>().map((t) => ChannelTab.fromString(t)).whereType<ChannelTab>().toList() ?? [],
);

YoutubePlaylist mapPlaylist(PlaylistDto d) => YoutubePlaylist(
  id: d.id, name: d.name, url: d.url,
  uploaderName: d.uploaderName,
  uploaderAvatars: d.uploaderAvatars?.whereType<String>().toList() ?? [],
  uploaderUrl: d.uploaderUrl,
  banners: d.banners?.whereType<String>().toList() ?? [],
  thumbnails: d.thumbnails?.whereType<String>().toList() ?? [],
  streamCount: d.streamCount ?? 0,
  description: d.description,
  playlistType: PlaylistType.fromString(d.playlistType),
);

YoutubeComment mapComment(CommentDto d) => YoutubeComment(
  author: d.author, commentText: d.commentText,
  uploadDate: d.uploadDate,
  uploaderAvatars: d.uploaderAvatars?.whereType<String>().toList() ?? [],
  uploaderUrl: d.uploaderUrl, commentId: d.commentId,
  likeCount: d.likeCount, hearted: d.hearted ?? false,
  pinned: d.pinned ?? false, replyCount: d.replyCount ?? 0,
  isChannelOwner: d.isChannelOwner ?? false,
  isUploaderVerified: d.isUploaderVerified ?? false,
  streamPosition: d.streamPosition,
);

CommentsPage mapCommentsPage(CommentsPageDto d) => CommentsPage(
  comments: d.comments?.whereType<CommentDto>().map(mapComment).toList() ?? [],
  hasNextPage: d.hasNextPage ?? false,
);

YoutubeVideo mapYoutubeVideo(VideoInfoDto info, StreamsDto streams) => YoutubeVideo(
  videoInfo: mapVideoInfo(info),
  audioOnlyStreams: streams.audioStreams?.whereType<AudioStreamDto>().map(mapAudio).toList() ?? [],
  videoOnlyStreams: streams.videoOnlyStreams?.whereType<VideoStreamDto>().map(mapVideoOnly).toList() ?? [],
  videoStreams: streams.videoStreams?.whereType<VideoStreamDto>().map(mapVideo).toList() ?? [],
  subtitleStreams: streams.subtitleStreams?.whereType<SubtitleStreamDto>().map(mapSubtitle).toList() ?? [],
  segments: streams.segments?.whereType<SegmentDto>().map(mapSegment).toList() ?? [],
  framesets: streams.framesets?.whereType<FramesetDto>().map(mapFrameset).toList() ?? [],
);
